### ISSUE TITLE
Support not bailing out when one of the _file_name_s isn't decryptable/encryptable in ansible-vault decrypt/encrypt

### ISSUE THREAD

**Issue by brlin-tw** [dockpack/ansible-vault#293]
Hello, I'm often required to decrypt multiple Ansible Vault encrypted files, work on them, and then encrypt them back again, but when I want to take a shortcut and use the `ansible-vault decrypt/encrypt *.yml` command to batch process these files `ansible-vault` will bail out when it found a file it can't process (because it is already decrypted/encrypted).

It would be great if the behavior can be changed/customized to make it ignore the file when the file can't be processed, thanks!

**Comment by brlin-tw** [comment]
## Workarounds

Write a script that checks whether the files are encrypt-able/decrypt-able before passing those who actually are to `ansible-vault encrypt/decrypt file_name...`.

The major logic is to determine whether the file is encrypted by Ansible Vault, which can be done using the following shell function:

```bash

# Check whether _file_ is encrypted Ansible Vault file
is_encrypted_file(){
    local file="${1}"

    # The dollar sign should be treated literally instead
    # shellcheck disable=SC2016
    if ! sed \
        -n \
        1p \
        "${file}" \
        | grep \
            -q \
            -F \
            '$ANSIBLE_VAULT;'; then
        return 1
    else
        return 0
    fi
}
```

**Comment by boldandbusted** [comment]
@brlin-tw  So, hmm... I think you are looking for Ansible's Vault feature, which is not what this role configures. This role is to configure HashiCorp Vault, not Ansible's Vault. Yes, the naming of these two useful tools is quite confusing and unfortunate... and collide in this excellent Role. :(

This is what you're talking about: https://docs.ansible.com/ansible/latest/user_guide/vault.html
This is what this Ansible Role configures: https://www.vaultproject.io/

Cheers. :)

**Comment by brlin-tw** [comment]
Thanks for your info, the name is surely confusing lmao.
