### ISSUE TITLE
Crashing at TASK [ansible-community.ansible-vault : OS packages] 

### ISSUE THREAD

**Issue by vacquah** [dockpack/ansible-vault#322]
I used this role to install successfully a few times. However now, I get this error consistently. It crashes when it gets to the "TASK [ansible-community.ansible-vault : OS packages] " stage. Been looking at it for a couple days so throwing it out here.

`TASK [ansible-community.ansible-vault : OS packages] *****************************************************************************************************************************************fatal: [10.1.20.10]: FAILED! => {"cache_update_time": 1670461863, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"       install 'acl=2.3.1-1'' failed: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/a/acl/acl_2.3.1-1_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "rc": 100, "stderr": "E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/a/acl/acl_2.3.1-1_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "stderr_lines": ["E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/a/acl/acl_2.3.1-1_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'", "E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following packages were automatically installed and are no longer required:\n  libflashrom1 libftdi1-2\nUse 'sudo apt autoremove' to remove them.\nThe following NEW packages will be installed:\n  acl\n0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.\nNeed to get 38.5 kB of archives.\nAfter this operation, 205 kB of additional disk space will be used.\nIgn:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 acl amd64 2.3.1-1\nIgn:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 acl amd64 2.3.1-1\nIgn:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 acl amd64 2.3.1-1\nErr:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 acl amd64 2.3.1-1\n  Temporary failure resolving 'archive.ubuntu.com'\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following packages were automatically installed and are no longer required:", "  libflashrom1 libftdi1-2", "Use 'sudo apt autoremove' to remove them.", "The following NEW packages will be installed:", "  acl", "0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.", "Need to get 38.5 kB of archives.", "After this operation, 205 kB of additional disk space will be used.", "Ign:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 acl amd64 2.3.1-1", "Ign:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 acl amd64 2.3.1-1", "Ign:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 acl amd64 2.3.1-1", "Err:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 acl amd64 2.3.1-1", "  Temporary failure resolving 'archive.ubuntu.com'"]}`

**Comment by FalcoSuessgott** [comment]
This look like its caused by your OS and not the Ansible role. You probably need to fix this using `apt`. Seems like the package `acl` breaks your system.
