### ISSUE TITLE
Ansible Module for crud operations with Vault?

### ISSUE THREAD

**Issue by darthVikes** [dockpack/ansible-vault#334]
Is there an Ansible Module for crud operations with Ansible Vault?   Want to be able to add new credentials into my Ansible vault? or delete old ones?

**Comment by FalcoSuessgott** [comment]
I use https://docs.ansible.com/ansible/latest/collections/community/hashi_vault/index.html and for not supported operations the ansible `uri` module

**Comment by darthVikes** [comment]
> I use https://docs.ansible.com/ansible/latest/collections/community/hashi_vault/index.html and for not supported operations the ansible `uri` module

Would introduce a dependence on Hashicorp Vault, and also assumes you have that set up.  Vs using a more Native Vault in Ansible Vault.

**Comment by FalcoSuessgott** [comment]
Soory read that wrong.. Well this repo is about installing and configuring Hashicorp Vault and doesnt have anything to do with Ansible Vault, its 2 different things
